version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  twitterc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: twitterc_container
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
      POSTGRES_HOST: postgres_container
      POSTGRES_PORT: 5432
    restart: unless-stopped

volumes:
  postgres_data: