version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: